'use client';
import { Montserrat, Roboto, Open_Sans, } from "next/font/google";
import "../styles/globals.css";
import ParticlesBackground from "./ParticlesBackground";
import Progress from "@/components/Progress";


const font = Open_Sans({ subsets: ["latin"], });

// export const metadata = {
//   title: "Jie Min Portfolio",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`${font.className} antialiased`}
      >
        <ParticlesBackground />
        <Progress />

        <main>
            {children}
        </main>

        {/* make this like https://i9gwuc.csb.app/ whne scrolling, you can feel like it will auto go to certain percentage */}
        {/* <motion.div className="fixed left-0 right-0 bottom-40 h-1 bg-[#4463ec]" style={{ scaleX }} /> */}
      </body>
    </html>
  );
}
